# Generated by Django 5.0.1 on 2026-01-12 03:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0008_healthrecord_attachment'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current wallet balance', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after this transaction', max_digits=10)),
                ('description', models.TextField(help_text='Transaction description')),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], default='wallet', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Related appointment if payment is for consultation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='appointments.appointment')),
                ('order', models.ForeignKey(blank=True, help_text='Related order if payment is for pharmacy order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pharmacy.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallets_tra_wallet__ec3627_idx'), models.Index(fields=['appointment'], name='wallets_tra_appoint_c3b8bb_idx'), models.Index(fields=['order'], name='wallets_tra_order_i_cbe3dd_idx'), models.Index(fields=['status'], name='wallets_tra_status_af050c_idx')],
            },
        ),
    ]
