# Generated by Django 5.0.1 on 2025-12-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctorschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_meet_link',
            field=models.URLField(blank=True, help_text='Google Meet link for video consultations', null=True),
        ),
    ]
