# Generated by Django 5.0.1 on 2025-12-27 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_doctor_clinic_address_doctor_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the health record')),
                ('title', models.CharField(help_text='Title or brief description', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the health record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Optional: Link to appointment if record was created during appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to='appointments.appointment')),
                ('created_by', models.ForeignKey(help_text='User who created this record (doctor or patient)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'date'], name='appointment_patient_93df75_idx'), models.Index(fields=['appointment'], name='appointment_appoint_afa1f4_idx')],
            },
        ),
    ]
