# Generated by Django 5.0.1 on 2025-12-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_healthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment (e.g., lab reports, images, documents)', null=True, upload_to='health_records/'),
        ),
    ]
